### ISSUE TITLE
Visual issue with semi theme

### ISSUE THREAD

**Issue by ykarpeev** [ArchLeaders/ConfigFactory#11]
Hello, if I install the semi theme the UI looks like this:

![image](https://github.com/ArchLeaders/ConfigFactory/assets/6986975/f6edf453-c449-4c14-baba-8c9f7a593320)

I changed the togglebutton style to have its background as

`Background="{DynamicResource ThemeBackgroundBrush}"
`
in ConfigPage.axaml. 

This makes it work correct for me on both themes 

Is this the correct fix or is the issue with the theme? Can I override the styles without changing the code? I would like to make the "General" text header be black as well.

**Comment by ArchLeaders** [comment]
ConfigFactory uses the resources from Avalonia's default FluentTheme. You can configure these brushes by overriding them in (or in this case adding them to) the application resources.

Eventually, I'll try to make custom brushes to make these easier to configure and understand, but this should fix the problem without editing the source code.

```xml
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.ThemeDictionaries>
            <ResourceDictionary x:Key="Light">
                <SolidColorBrush x:Key="SystemChromeHighColor">#FFACACAC</SolidColorBrush>
                <SolidColorBrush x:Key="SystemChromeLowColor">Transparent</SolidColorBrush>
                <SolidColorBrush x:Key="SystemChromeMediumColor">#FFF2F2F2</SolidColorBrush>
                <SolidColorBrush x:Key="SystemChromeMediumLowColor">#FFE6E6E6</SolidColorBrush>
            </ResourceDictionary>
            <ResourceDictionary x:Key="Dark">
                <SolidColorBrush x:Key="SystemChromeHighColor">#FF737373</SolidColorBrush>
                <SolidColorBrush x:Key="SystemChromeLowColor">Transparent</SolidColorBrush>
                <SolidColorBrush x:Key="SystemChromeMediumColor">#FF2B2B2B</SolidColorBrush>
                <SolidColorBrush x:Key="SystemChromeMediumLowColor">#FF1F1F1F</SolidColorBrush>
            </ResourceDictionary>
        </ResourceDictionary.ThemeDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

You can hardcode the colours like I have done, or reference brushes from semi theme.
