### ISSUE TITLE
Question regarding this package 

### ISSUE THREAD

**Issue by DentyTxR** [ArchLeaders/ConfigFactory#12]
I'm pretty new with app development and I pretty much self taught myself c#, I'm having a bit of a hard time setting everything up, but I mostly got it working (I think), but my question is do I have to create my own methods for reading the settings json or is there a easier and already available method?

**Comment by ArchLeaders** [comment]
The [ConfigModule<T>](https://github.com/ArchLeaders/ConfigFactory/blob/master/src/ConfigFactory.Core/ConfigModule.cs) abstract class handles the [Save](https://github.com/ArchLeaders/ConfigFactory/blob/master/src/ConfigFactory.Core/ConfigModule.cs#L97-L105) and [Load](https://github.com/ArchLeaders/ConfigFactory/blob/master/src/ConfigFactory.Core/ConfigModule.cs#L66-L85) implementations.

This implementation stores the settings as json in `%localappdata%`\\[`{Name}`](https://github.com/ArchLeaders/ConfigFactory/blob/master/src/ConfigFactory.Core/ConfigModule.cs#L34)\\`Config.json`

I'll close this issue as completed, but feel free to leave more comments if you have more questions.
