### ISSUE TITLE
Feature localizations

### ISSUE THREAD

**Issue by UralMichael** [ArchLeaders/ConfigFactory#2]
Hello @ArchLeaders ,

I've noted your [NxEditor project](https://github.com/NX-Editor/NxEditor) while exploring Avalonia projects.
It is a great example of Avalonia capabilities. I am working on quite the same type of application and want to contribute to this forms generator.

The feature I miss at the moment is ability to localize strings that you pass in the `ConfigAttribute`.

I suggest a basic implementation #1 that adds just one method to the base `IConfigModule `interface.
The core implementation of the method simply returns the same string.
However, the actual implementation completely relies on the user.

I added example of usage to the Demo project.

**Comment by ArchLeaders** [comment]
Just reviewing your PR now. So far so good, I'm mostly wondering if we can reduce the need for boiler-plate code with the translation implementation. Also looks like there might be some odd behavior in the group/category lookup that I'll need to look into.

**Comment by UralMichael** [comment]
To make sure that the group/category lookup behavior remains the same I added the `_id` property to the group and category.

As we speak about boiler-plate code, I am not sure that Avalonia has a standardized way to implement i18n.
That is why I suggest to leave the actual implementation to the user.

**Comment by ArchLeaders** [comment]
> To make sure that the group/category lookup behavior remains the same I added the _id property to the group and category.

I see, I noticed that field had been added, but I couldn't see it in the lookup function. I'll check more thoroughly when I review it though.

**Comment by ArchLeaders** [comment]
> As we speak about boiler-plate code, I am not sure that Avalonia has a standardized way to implement i18n.
That is why I suggest to leave the actual implementation to the user.

I was thinking we could implement our own standard, like I did with `ConfigFactory<T>`. You can still implement `IConfigFactory`, but you can use `ConfigFactory<T>` to use the standard.

**Comment by UralMichael** [comment]
> I was thinking we could implement our own  standard

Here is a detatiled [topic ](https://github.com/AvaloniaUI/Avalonia/discussions/8741) related to the issue.
That [implementation ](https://www.sakya.it/wordpress/avalonia-ui-framework-localization/) also seems good.

Personally, I have not yet decided which way is better.

**Comment by ArchLeaders** [comment]
Yeah, just looking at those implementations too. I personally like the idea of using dynamic resources, only issue being the possible complexity of implementing translations.

Because writing files like [this](https://github.com/timunie/Tims.Avalonia.Samples/blob/main/src/LocalizationSample/Assets/Lang/de-DE.axaml) is a bit annoying. Source generation could help with that though.

**Comment by ArchLeaders** [comment]
Merged in https://github.com/ArchLeaders/ConfigFactory/commit/fc1a85490aca99e0dee61f4fe3b10e8d683ab6f8
