### ISSUE TITLE
Numeric Dropdown

### ISSUE THREAD

**Issue by UralMichael** [ArchLeaders/ConfigFactory#3]
### The issue.

For example, I have an integer property that represents Speed.
I want to have a dropdown that has 3 options for the Speed: Slow (10), Medium (50), Fast (100).

### Solution.
I suggest this implementation #4 

Here are list of changes:
1) Modified `DropdownConfigAttribute` to be able to use properties `DisplayMember` and `SelectedValue` of the Avalonia `ComboBox` control.

2) Seperated `ComboBox` logic from the `TextControlBuilder`, because it is common for all types.

3) Added `NumericControlBuilder` for numeric type properties. A numeric property may have optional `NumericConfigAttribute` to control properties `Minimum`, `Maximum` and `Increment` of the Avalonia `NumericUpDown` control.

4) Updated demo project to seperate Dropdown examples.

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/ArchLeaders/ConfigFactory/commit/3f25b6a2a83adaca1ce1a44163e0833e790017c3
