### ISSUE TITLE
Make ConfigModule<T>.Load() an abstract function

### ISSUE THREAD

**Issue by Kermel** [ArchLeaders/ConfigFactory#7]
Hi, I was experimenting a bit more with the ConfigModule and custom implementations of the ControlBuilder - I have created a custom builder that creates a combobox that is being filled with my custom data structure and the combobox items consist of an Icon (Bitmap inside) and a label (simply a flag icon with the name of the language).

But there is a problem with Saving and Loading the configuration. The default serialization mechanism doesn't correctly serialzie the combobox contents (selected language) and it always fails when Loading the contents from the stored Json (initializing of the inner Bitmap fails).
(The reason is that one of my configurable ObservableProperties is a field with my custom type "LanguageItemModel" from the combobox containing the bitmap for composing the combobox contents in the Builder) and I cannot mark it as [JsonIgnore]d since it is generated -> so I need to implement some non-default serialization mechanism with first remapping the values to be serialized and stored and only serialize such remapped object (and vice versa for Loading back)

I would need in my case to override the Saving and Loading mechanism completely i.e. not to save the combobox contents (as it can be always initialized), also the "selectedLanguage" is not needed to be stored as a whole model object (icon + label) but just as a langauge code (i.e. the real "value" from the combobox).

Now I'm solving it myself as follows
- Saving is kept as default, doing the default json serialization but right after Save I added my custom mapping of the ConfigModule contents to a "Configuration object" that is then serialized itself.
- I never initialize the model via the .Shared property (i.e. to avoid calling Load() method) but I'm rather creating a new instance and immediately doing my custom mapping back from the custom serialized "Configuration object"
- Such initializaed ConfigModule is then "Appended" to the ConfigModel as usually

However it might be more elegant if I could just override both the Save and Load methods and do my serialization and loading from there.
(I might try to modify the codebase myself and issue a pull request? It seems like a rather simple fix)

**Comment by ArchLeaders** [comment]
I'm not sure why I hid `Load()`, it doesn't look like I had any good reason, so that shouldn't be an issue.

However, you could also create your own [`IConfigModule`](https://github.com/ArchLeaders/ConfigFactory/blob/master/src/ConfigFactory.Core/IConfigModule.cs) implementation, `ConfigModule<T>` is only designed for simple JSON configurations.

At any rate, a PR is most welcome if you're up for it.

**Comment by Kermel** [comment]
You are probably right, I will consider implementing my module completely from scratch from IConfigModule. I have to take a look on what all is needed.

I'll try that pull request sometime, hopefully later this week when I have time to look at it :)

**Comment by Kermel** [comment]
Okay, pull request on the way. Let me know in case there is some issue :-)

**Comment by Kermel** [comment]
Finished.

**Comment by Kermel** [comment]
@ArchLeaders - could you please publish an updated NuGet library? I would use the new virtualized Load() method possibiltiy right away :-)

**Comment by ArchLeaders** [comment]
Just doing some quick fixes then I'll publish. Should be within the hour.

**Comment by ArchLeaders** [comment]
Made some changes so that `Shared` uses the virtual `Load` method.

```cs
private static readonly Lazy<T> _shared = new(() => {
    T module = new();
    module.Load(ref module);
    return module;
});
```

The only difference is the API, it now takes a `ref T module` instead of returning `T`

```cs
protected virtual void Load(ref T module)
{
    if (!File.Exists(module.LocalPath)) {
        module.Save();
        return;
    }

    using FileStream fs = File.OpenRead(module.LocalPath);
    module = JsonSerializer.Deserialize<T>(fs)!;

    foreach (var (name, (property, _)) in module.Properties) {
        typeof(T).GetMethod($"On{name}Changed", BindingFlags.NonPublic | BindingFlags.Instance)?
            .Invoke(module, [property.GetValue(module)]);
    }
}
```

I also removed `IConfigModule Load()` from the `IConfigModule` interface because I don't think it should ever be accessed there.

Any objections to this implementation?

**Comment by Kermel** [comment]
So if I get it correctly - now the Module would be loaded via the "Shared" property and not expicitly via calling the "Load" method anymore?
(I'm not sure this is OK since when I have possibility to "Save" (serialize) I should probably be able also to "Load" (deserialize), maybe?

(I do not see it in the code, just thinking out loud about the possibilities... so there will still be the "Save" interface method with the default out-of-the-box implementation + the possibility of overriding to serve more complex logic; and I just think about the necessity to "Load" the model from anywhere but the model itself (which might be done only if the Load method is provided by the interface)... (really not sure about whether it is necessary or not)

**Comment by ArchLeaders** [comment]
> So if I get it correctly - now the Module would be loaded via the "Shared" property and not expicitly via calling the "Load" method anymore?

Correct, as it's a singleton, it should only be loaded once.

`Load()` can also be used in your implementation (as it's protected) to deserialize into `T`. It's just not publicly exposed.

**Comment by ArchLeaders** [comment]
> (I do not see it in the code, just thinking out loud about the possibilities... so there will still be the "Save" interface method with the default out-of-the-box implementation + the possibility of overriding to serve more complex logic; and I just think about the necessity to "Load" the model from anywhere but the model itself (which might be done only if the Load method is provided by the interface)... (really not sure about whether it is necessary or not)

I share your sentiment. I don't think it should be exposed, but at the same time hiding it might be redundant.

I think I'll expose it again until I have a real reason to hide it.

**Comment by Kermel** [comment]
Perfect, let me please know once you published the new library version :) (in nuget I can still see only 0.3.2 but here it says 0.4.0 is available)
